[package]
name = "ax1600i"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rusb = "0.9"  # Replace libusb with rusb
crc = "3.0.1"
